apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: s1-simple-application/nginx
    repoURL: 'https://github.com/AlirezaBahadoriZadeh2002/argocd-projects.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated: null
