apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-app
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
          #    directory:
          #      exclude: 'service.yml'
          #      include: '{serviceaccount.yml,service.yml}'
          #      recurse: true
    path: s1-simple-application/nginx
    repoURL: https://github.com/AlirezaBahadoriZadeh2002/argocd-projects.git
    targetRevision: main
